apiVersion: v1
kind: Service
metadata:
 name: hypermedia-app-service
 labels:
  name: hypermedia-app-service
  app: hypermedia-app
spec: 
 ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
 selector:
  name: hypermedia-app-pod
  app: hypermedia-app
 type: NodePort