apiVersion: v1
kind: Service
metadata:
 name: sqldata
 labels:
  name: sqldata-service
  app: hypermedia-app
spec: 
 ports:
  - port: 1433
    targetPort: 1433
 selector:
  name: sqldata-pod
  app: hypermedia-app
 type: ClusterIP